### ISSUE TITLE
Only make plex matches for certain series? 

### ISSUE THREAD

**Issue by Eagle1337** [johnkiddjr/PlexMatch-File-Generator#37]
I only need it for one series,and I don't want to clutter everything else.

**Comment by johnkiddjr** [comment]
This will require additional work, but I will add the ability to specify series as a command line switch in the next release, but in a future release I'll add support for a config file that allows specifying all program settings instead of needing them to come from the command line, which would make this usable to someone needing to specify 50 shows out of 300 for instance.

**Comment by johnkiddjr** [comment]
Closed with release 0.9.2-rc2, though will partially continue to be worked on in #42
