### ISSUE TITLE
Request: Process only a single library (or folder tree)

### ISSUE THREAD

**Issue by efalsken** [johnkiddjr/PlexMatch-File-Generator#38]
I've got multiple libraries, and it's clear that this tool (and plex) doesn't handle co-habitating movies very well (#15), but it always processes my Movies library first. I'd like to say "only process this folder".

suggest `--library MyStuff` or `-l MyStuff`

**Comment by johnkiddjr** [comment]
Co-habitating movies is a big problem, that I'm still trying to find a good solve for. If Plex supported the plexmatch file having any name we want as long as it ended in .plexmatch it would be a really easy fix.

That said, I like this request because I can just allow the library flag to be added multiple times if you want to specify more than 1 library at a time.

I'll try to look at and implement a way to limit libraries this week. Folders is more difficult, since I get all the data from Plex and only use the filesystem to write.. but I can look into that later in the future.

**Comment by efalsken** [comment]
Yeah. I figured it would be easier than trying overlap the open issue with Movies.

One thing that I ALMOST got working.... you can almost use the tool to create a whole new empty directory tree by mapping to a completely new folder..... but it really doesn't like the folders not existing. I can see mapping it to a new (empty) directory tree might be a useful way to "test" the app to see what sort of data it creates without needing to recreate my whole library folder structure a second time. maybe a `--create` option?

**Comment by johnkiddjr** [comment]
This enhancement has been added and is scheduled to be released with next release (probably this weekend)

**Comment by johnkiddjr** [comment]
Closed with release 0.9.2-rc2
