### ISSUE TITLE
Generating .plexmatch for each season too

### ISSUE THREAD

**Issue by grzegor** [johnkiddjr/PlexMatch-File-Generator#39]
Some shows have multiple episodes ordering, for example Firefly: on the [DVD release](https://thetvdb.com/series/firefly/seasons/dvd/1) the first episode is "Serenity" but on the bullshi... erm... [air date order](https://thetvdb.com/series/firefly/seasons/official/1) the first episode is "The Train Job". Unfortuanetely Plex defaults always to air date order, but luckily each show order have it's own respectable Plex GUID. 

Trivial fix would be making .plexmatch file in each season folder, for example if someone forced DVD order for Firefly in Plex then the .plexmatch file should contain "Guid: plex://season/602e67e966dfdb002c0a1b72" , if someone left it as air date order it's going to be "Guid: plex://season/602e67e766dfdb002c0a1b5b" (tested this by creating the files manualy, it works as expected, Plex scanner picked the corret order each time).

**Comment by johnkiddjr** [comment]
It's odd that they use the same show guid no matter what the sorting is and use different guid for each season when the show is set to something other than the default library sorting... that said this is something that can be implemented for the next version.

The "trivial fix" you mentioned would roughly halve performance since it would double the API calls per media item, but I will be adding a new command line switch to enable per season processing for all items if wanted, and the default behavior will be changed to do per season processing only on media items that have episode ordering set to anything other than the default. This would result in a show plexmatch, and each season having its own plexmatch as well. I'll also be including the season number in the season plexmatch files, which would make this a very good option for someone using non-standard naming on their season folders as well.

Still find this so weird. If episode ordering is set per show, why make the guid difference per season? You can't even set ordering per season so it doesn't make sense.

**Comment by johnkiddjr** [comment]
Working on the release for this feature now, when used automatically or by enabling the option it will show up like this in the log:

<img width="848" alt="image" src="https://github.com/johnkiddjr/PlexMatch-File-Generator/assets/25515484/cfdbd178-99f3-4511-bb42-f6a65283e434">

This shows that the main show plexmatch was written, and the season file was written too. Since a season can technically be split between many different folders the path the file was written to is also printed out.

**Comment by johnkiddjr** [comment]
Closed with release 0.9.2-rc2
